"""Embed the rendered pipeline diagram in the primer, between <!-- pipeline:start --> and <!-- pipeline:end -->.

    uv run python docs/teach/diagrams/embed_pipeline.py

Reads docs/teach/benchmark-pipeline.html (archify render plus raxit_theme.py), takes its SVG and the style rules the
SVG uses, scopes those rules to #pipeline-diagram with the raxIT light palette, and writes them into the primer.
Re-run after re-rendering the diagram. The standalone page keeps the theme toggle and PNG/SVG export.
"""
import re
from pathlib import Path

from raxit_theme import LIGHT

TEACH = Path(__file__).resolve().parents[1]
SRC, PRIMER = TEACH / "benchmark-pipeline.html", TEACH / "gold-rails-primer.html"


def main() -> None:
    s = SRC.read_text(encoding="utf-8")
    svg = re.search(r"<svg viewBox=.*?</svg>", s, re.S).group(0)
    svg = svg.replace(" — ", ". ").replace("—", ",")
    svg = svg.replace("<svg ", '<svg class="pipeline-svg" ', 1)
    rules = re.search(r"(    \.c-grid .*?\.c-lane [^\n]*\n)", s, re.S).group(1)
    scoped = "\n".join(("#pipeline-diagram " + ln.strip()) if ln.strip().startswith(".") else ln.strip()
                       for ln in rules.splitlines() if ln.strip() and not ln.strip().startswith("/*"))
    vars_ = " ".join(f"{k}: {v};" for k, v in LIGHT.items())
    block = ("<!-- pipeline:start (generated by docs/teach/diagrams/embed_pipeline.py; edit the JSON and re-run) -->\n"
             f"<style>\n#pipeline-diagram {{ {vars_} }}\n"
             "#pipeline-diagram svg.pipeline-svg { width: 100%; height: auto; font-family: var(--font-body); }\n"
             f"{scoped}\n</style>\n"
             f'<div id="pipeline-diagram" class="frame scroll wide-svg">{svg}</div>\n'
             "<!-- pipeline:end -->")
    p = PRIMER.read_text(encoding="utf-8")
    new, n = re.subn(r"<!-- pipeline:start.*?<!-- pipeline:end -->", lambda m: block, p, flags=re.S)
    assert n == 1, "primer markers not found"
    PRIMER.write_text(new, encoding="utf-8")
    print(f"embedded {len(svg):,} bytes of SVG in {PRIMER.name}")


if __name__ == "__main__":
    main()
